### ISSUE TITLE
No support for Windows guests

### ISSUE THREAD

**Issue by AlexAltea** [intel/haxm#118]
I have tried running a Windows 10 ISO (v1804, 64-bit) image on stock QEMU v2.12.50 + HAXM v7.3.2.
However, it seems to get stuck during the kernel boot sequence, i.e. the one with black background and a blue Windows logo. After few minutes, the host kernel crashes (which is also Windows 10 64-bit).
This also affects older Windows versions, such as Windows 7.

I have noticed that previous attempts to run Windows guests where unsuccessful, see #45. However, back then it was due to unsupported instruction emulation, which nowadays has been vastly improved. Do you know what might be causing this? If not, I can always investigate this.

I would be happy to submit a patch adding support for Windows guests myself. Feel free to point me in the right direction if you have any extra information!

**Comment by raphaelning** [comment]
Thanks, this would be a very useful feature/enhancement for HAXM. I've never tried booting a Windows guest myself, so I can't be of much help at the moment...

> However, it seems to get stuck during the kernel boot sequence, i.e. the one with black background and a blue Windows logo.

Wow, to me that's already some progress made, thanks to #42!

> After few minutes, the host kernel crashes (which is also Windows 10 64-bit).

This is bad, but at least it can be the starting point of your investigation :) For your convenience, here is `IntelHaxm.pdb` for the HAXM 7.3.2 release, which you can use to resolve symbols when analyzing the BSOD dump with WinDbg. Of course, you can also rebuild `IntelHaxm.sys` yourself and obtain the matching `.pdb`, or debug this issue on Linux.

**Comment by raphaelning** [comment]
@AlexAltea One of the things that prevent HAXM from booting a Windows (x86_64) guest is the lack of proper CR8 virtualization. See https://github.com/intel/haxm/pull/145#issuecomment-446910031 and #145.

**Comment by AlexAltea** [comment]
@raphaelning Nice catch! I'll look into CR8 virtualization. Hopefully that will make it progress further.

**Comment by raphaelning** [comment]
@AlexAltea Thanks. I realized that one of the links I gave you above was wrong, and have fixed it, but you get the idea :-) I think the main challenges are:

1. API change. Since the real CR8 (Task Priority Register, or TPR) is emulated in user space, we may need a new interface for exchanging CR8 state with user space (e.g. adding a new `HAX_EXIT_xxx` status code). But is it possible to avoid an API change at all? One idea is to translate the CR8 access to an MMIO on the TPR in the emulated APIC device, but I guess the MMIO address depends on the APIC device model.
2. Efficiency. I suppose Windows x86_64 accesses CR8 very often, so if we make an exit to QEMU for every CR8 read/write, the performance won't be good. Does efficient CR8 virtualization require implementing APIC virtualization in HAXM (similar to KVM's in-kernel IRQ chip)?

I'll be on vacation next week, but please feel free to submit a PR or proposal, and I'll review it when I'm back.

**Comment by raphaelning** [comment]
Update: #180 has confirmed that it is the lack of CR8 virtualization that crashes the 64-bit Windows 10 guest. There's no more host crash.

**Comment by FreddMadison** [comment]
According to reverse engineering of Win10x64 bootloader, CR8 is result of BugCheck and windows installation is stuck because of "// pat is disabled!" in vcpu.c
Could you provide some quick answer why it was disabled in current implementation ? Does it contradict with current memory management implementation ?

**Comment by coxuintel** [comment]
I can’t find the history why it’s disabled in current implementation.
@nevilad is working PR#204 to add PAT support. Once some BSOD issues resolved, we’ll merge related patches into mainline.

--
Best Regards,
Colin Xu

**Comment by nevilad** [comment]
How did Fred Madison reverse engineered Win10x64 bootloader? Before I added PAT\cr8 support it was stuck and it was easier to find what it checks. Now it runs in an ethernal cycle. Any ideas how to reverse engineer this?

**Comment by FreddMadison** [comment]
It was useless, since I did not find branch nevilad:win10_support yet. After cpuid fix I cant find this ethernal cycle as well, so I drop it.
Just in case someone knows how to attach WinDbg to Win10 kernel on qemu empty hda vm - it would be possible to move on. For now, qemu fails to install Win10 even in software mode and does not have com2pipe support.

**Comment by FreddMadison** [comment]
Obviously, since Intel is very concentrated on Android support and haxm comparing to kvm/arch/x86/kvm impl is very very far behind we may see win10x64 support in haxm in several years or never

**Comment by nevilad** [comment]
>It was useless, since I did not find branch nevilad:win10_support yet

https://github.com/nevilad/haxm/tree/win10_support. It supports win10x86, it works on my machine, but Colin says that it fails on Intel machines and he has no time to solve this. It is was forked on May.

>For now, qemu fails to install Win10 even in software mode

software mode - tcg? I add "-cpu core2duo" to qemu command line and Win10x64 installation works.

>kvm/arch/x86/kvm impl is very very far behind we may see win10x64 support in haxm in several years or never

So far I understand, Intel does not add support to guests other than Android. This is done by the community. I'm trying to add it now.

>someone knows how to attach WinDbg to Win10 kernel on qemu empty hda vm - it would be possible to move on. 

@AlexAltea added debugging support to haxm, maybe he knows how to do this?

**Comment by AlexAltea** [comment]
@nevilad My patch added agentless debugging support similar to the one in KVM. This allows for the host to set software/hardware breakpoints in arbitrary virtual addresses without requiring guest cooperation.

This allows to create a GDB server via the QEMU option `-s`, but it's *not* compatible with WinDbg.

**Comment by nevilad** [comment]
To debug win10 installation there must be a debugger server running in the installator. I found only descriptions how to start an already installed OS with debugger server running.
It seems that debugging with gdb is the only feasible solution.

**Comment by nevilad** [comment]
I've tried to run qemu with -s option and debug the guest with gdb and IDA. Both connected successfully.
Gbd was unable to debug a binary without symbol info - step command did nothing, there were no vm-entries. When I ran the guest (c command in gdb), it ran, but it was impossible anymore to give commands to gdb, so it was impossible to break the execution.
IDA saw wrong registers - RIP was zero, stepping into\over ran the guest and did not execute just one instruction.
@AlexAltea how did you test attaching to the remote gdb server feature?

**Comment by AlexAltea** [comment]
@nevilad First I run QEMU with the GDB server enabled (`-s`), paused (`-S`), and using the HAXM accelerator (`-accel hax`). Then I open a kernel image with IDA Pro, connect to GDB server at *localhost:1234* (default port for QEMU's GDB server). The advantages of using IDA are the integrated decompiler for closed-source kernels, graph view for assembly, a fancy GUI, and other fancy tools/plugins that I'm already used to.

Of course, if you don't have/want an IDA license, you can just use GDB client. Here's a sample script that I used to automatically connect to my targets spawned with QEMU:
https://github.com/AlexAltea/orbital/blob/master/tools/gdb/debug-kernel.gdb

The important bit is `target remote localhost:1234` (you can also type it manually after running `gdb`).

**Comment by nevilad** [comment]
Is it possible not to open the image in IDA and let it get the code directly from the execution? I want debug a very early stage of the OS installer and don't know which binary executes. When it is not possible, I have to analyze the windows installation disk to get the binary.
And it is not possible to disable ASLR in windows kernel.

**Comment by AlexAltea** [comment]
> Is it possible not to open the image in IDA and let it get the code directly from the execution?

Not sure. I've never tried to attach to Windows guests (as you pointed out KASLR is nearly impossible to disable, or at least it was last time I tried). I suppose plain GDB will always work, but it's of course not as comfortable as IDA.

**Comment by josephernest** [comment]
@AlexAltea @nevilad

Could you post a TL;DR about how to use **QEMU + haxm + Windows guest + Windows host**?

It still fails for me after many attempts (see https://github.com/intel/haxm/issues/307).

Thanks a lot in advance! I think it would be useful for many people...

**Comment by nevilad** [comment]
Install qemu and haxm on windows host. Then run it, for example so:
`qemu-system-i386.exe -L C:\user\qemu\pc-bios\ -name win7 -machine pc-i440fx-3.0 -usb -device usb-kbd -device usb-tablet -m 4G -vga std -rtc base=localtime -accel hax -hdc qemu_win7.qcow2 -cdrom Win7.iso`

I think your problem is due to a bug in haxm, DebugView log will shed light on the reason.

**Comment by nevilad** [comment]
I've done some tests with win10 x64. I've logged all vmexits after the beginning of the ethernal cycle and found that there are many ept_violations. I've suggested that the handler may emulate the ops wrong, logged ept_violation instruction opcodes and manually checked these. Their handling was correct.

I've also added debugging support to qemu+haxm, but was unable to debug it, since mingw gdb does not handle code selectors with nonzero base - it reads memory at eip and does not add cs base to it, ending in reading wrong memory. Is there any other gdb protocol supporting debugger for windows?
