### ISSUE TITLE
Intel Haxm download error by virtualization and hyper-v

### ISSUE THREAD

**Issue by abdulvahidcetinturk** [intel/haxm#183]
I did pretty much everything mentioned about this problem from many sources. But I still get the same error. I am trying to download haxm for androidstudio. I cannot continue without intelhaxm. Things I've done are mentioned below.

![image](https://user-images.githubusercontent.com/46319061/53020629-fc3e7580-345f-11e9-963a-b6f894e33afd.png)

This is processor specs.

![lenovospecs](https://user-images.githubusercontent.com/46319061/53020834-78d15400-3460-11e9-8b38-1a5dd8ca197b.png)

Hyper-v is already disabled from features and in command.

![hypervclosed](https://user-images.githubusercontent.com/46319061/53020975-d1085600-3460-11e9-9220-df7d4d9d2ba8.png)
![hypervclosedcommand](https://user-images.githubusercontent.com/46319061/53021147-2fcdcf80-3461-11e9-906a-e949e968ee46.png)

I've used the Device Guard and Credential Guard hardware readiness tool as well.

![credentialguard](https://user-images.githubusercontent.com/46319061/53021273-85a27780-3461-11e9-8c62-3eab9f6e9dff.png)

Virtualization is enabled when I check through task manager. But I cannot access enabling virtualization through BIOS setting because it does not show up. 

![virtualization](https://user-images.githubusercontent.com/46319061/53021417-d619d500-3461-11e9-8f83-0854f92150a3.png)

Working for a solution for 5 days but still no progress. I disabled the antivirus program as well. I guess I do something wrong or missing sth important. Is there any other issues that can prevent downloading haxm ?
Helps are appreciated. Thanks.

**Comment by raphaelning** [comment]
Thanks for the detailed report. You've downloaded HAXM but have not been able to install it. And that is because you have an AMD CPU, as shown in your second screenshot. HAXM only supports Intel CPUs at this time.

You may want to turn Hyper-V back on and try to use Windows Hypervisor Platform as an alternative accelerator for Android Emulator:

https://developer.android.com/studio/run/emulator-acceleration#vm-windows

We can't help you further. You can reach out to Android Studio support: https://developer.android.com/studio/report-bugs#emulator-bugs
