### ISSUE TITLE
VT not supported (svm enabled - hyper-v disabled)

### ISSUE THREAD

**Issue by kocagozcem** [intel/haxm#200]
Hey, im trying to install haxm for android studio emulator but i get vt not supported error. It was working well before but yesterday i tried to install mac os to my virtual machine from some different sources so im not sure what did i changed. This morning i tried to use android studio and then i get x86 error. i recovered my pc and deleted everything but this problem didnt fixed i cannot install haxm now. could you please help me?

**Comment by krytarowski** [comment]
AMD cpu is not supported.

**Comment by kocagozcem** [comment]
are you sure? because i was using it until yesterday?

**Comment by krytarowski** [comment]
yes.

**Comment by dantheman213** [comment]
Why isn't AMD CPU supported? It uses the same instruction set as Intel CPUs that are targeted. This is a core piece of software in current Android development SDLC. Are you saying that in order to develop Android apps you need to use Intel CPU and everyone else is just out of luck?

**Comment by wayne-ma** [comment]
@dantheman213 ,so far HAXM is designed and supported for CPU only.

**Comment by wcwang** [comment]
HAXM only supports Intel CPU and leverages Intel VT-x. This project is mainly initiated by Intel. Whether it supports other CPUs depends on the development status of other manufacturers. Any diverse contributions from community or other manufacturers are also welcomed.

**Comment by dantheman213** [comment]
So what you're saying is that the Android SDK team should NOT be using Intel's technology because Intel refuses to support all common and trivially configured CPUs or computers in which it could run under?

**Comment by wcwang** [comment]
Thanks for your comments. Android SDK recommends users to use HAXM when they are using Intel CPU on Windows. HAXM project team has rather limited resources to cover all CPUs other than Intel's. We cannot guarantee the availability for all other CPUs which use Intel technology. Any software has its usability scope, and HAXM has already clearly declared its supporting cases on the homepage. The contributions from community for the mentioned supports will always be welcomed. Thanks.

**Comment by dantheman213** [comment]
I understand this not your decision to unilaterally make. However, I'd like to clear up one thing:

> Android SDK recommends users to use HAXM when they are using Intel CPU on Windows.

This is not the case. There is no viable option right now for AMD Ryzen users to run, debug, or test Android apps because AVD requires HAXM to be installed to run x86 Android Emulator. And even though I am using high-end motherboards that support VT-x and I can run software like Hyper-V, Docker, and VirtualBox, I cannot run HAXM on any AMD Ryzen machine I've tried.

Here is the only alternative that I have found: 

https://stackoverflow.com/questions/27471219/can-i-run-an-emulator-without-haxm-in-android-studio

So I followed the instructions and....

<img width="283" alt="2" src="https://user-images.githubusercontent.com/10934533/74214677-3d243100-4c53-11ea-95b7-9433b441a3ea.PNG">

OK, fine, but can I develop on it ? What kind of performance can I expect? Well, it's been about 30 mins since I booted up the ARM emulator on a 16 thread, 4GHz CPU and it just finished booting up now. I'm getting about 0.1 fps while trying to navigate. It's basically unusable.

**Conclusion**
The decision for Android team to use HAXM and the subsequent decision for Intel to not support AMD's popular and powerful Ryzen CPUs that use the same instruction set (x86)  is a grave combo decision that has huge impacts to the developer community. Let us hope that AMD doesn't produce some software at some point that locks out Intel users on an important development platform. 

I hope in time that Intel and/or the HAXM team will reconsider this decision.
