### ISSUE TITLE
No v7.5.1 macOS build

### ISSUE THREAD

**Issue by merlin-zaraza** [intel/haxm#206]
There are no v7.5.1 macOS build

**Comment by robertleeblairjr** [comment]
Yep. I was looking to update to 7.5.1, as well. There may be a delay this time since kexts must be notarized for proper install in macOS 10.14.x. Perhaps, one of the developers will comment that they are currently having releases notarized and to simply wait for the build on the releases page in the near future. There is a method to build with Xcode using specific SDKs. However, unless you can sign with an Apple Developer ID and can have it notarized, then you're probably going to experience the problems of the kext not loading without a workaround.

[https://github.com/intel/haxm/blob/master/docs/manual-macos.md](url)

**Comment by wcwang** [comment]
Sure, just as you mentioned, we are following the process of kext notarization for macOS 10.14.5. Currently, we can notarize the HAXM v7.5.1 properly and the macOS release package is under testing. We will also release this version in a week. Thanks for your attention.

**Comment by robertleeblairjr** [comment]
> Sure, just as you mentioned, we are following the process of kext notarization for macOS 10.14.5. Currently, we can notarize the HAXM v7.5.1 properly and the macOS release package is under testing. We will also release this version in a week. Thanks for your attention.

Awesome. Thanks for the update. Have a good day.

**Comment by wcwang** [comment]
HAXM v7.5.1 release for macOS has been uploaded. Thanks.
