### ISSUE TITLE
Cannot Install HAXM (7.5.1) in Windows 10 1903 

### ISSUE THREAD

**Issue by neupaneanish** [intel/haxm#207]

**Comment by coxuintel** [comment]
Could you provide more information that may help us identify the issue?
Like:
"Application" and "System" logs in Event Viewer.
haxm_install*.log in %TEMP%.
...

**Comment by neupaneanish** [comment]
=== Logging started: 5/30/2019  7:33:31 ===
This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed. 
Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information.

=== Logging stopped: 5/30/2019  7:33:31 ===



![android](https://user-images.githubusercontent.com/26538899/58602774-d40bb180-82ad-11e9-850a-a468ac0841b6.png)
![defender](https://user-images.githubusercontent.com/26538899/58602775-d40bb180-82ad-11e9-8981-306f78845106.png)
![haxm](https://user-images.githubusercontent.com/26538899/58602776-d40bb180-82ad-11e9-9186-1ce3970620aa.png)
![hyperv](https://user-images.githubusercontent.com/26538899/58602777-d4a44800-82ad-11e9-925f-dfe09267b4b0.png)
![system](https://user-images.githubusercontent.com/26538899/58602778-d4a44800-82ad-11e9-969a-9eeff2b83dc7.png)

**Comment by coxuintel** [comment]
Would you also help run "haxm_check.exe" from an administrative cmd prompt and paste the result? It's also helpful if you can paste the last several lines from "systeminfo.exe" about Hyper-V.

I assume that you already verified the VT settings in BIOS are correct and HAXM works in prior Windows 10 builds like 1809. Correct me if there's any information missing.

We'll try on this new Windows 10 RS6 build, which ships some virtualization related updates, no sure the failure is caused by them.

**Comment by Omico** [comment]
The same problem, after run `haxm_check.exe`:
```
VT support -- no
NX support -- yes
```

**Comment by coxuintel** [comment]
Did you enabled Windows Sandbox? If you did, try to disable it first and check haxm_check, Intel® Processor Identification Utility again.

I just tried Windows 10 1903, find that in order to install/enable HAXM, both Hyper-V and Windows Sandbox have to be disabled. Windows Sandbox is also based on WHPX technology thus can't be enabled with HAXM at the same time. You may need a pure restart instead of fast startup after disabling Windows Sandbox.

**Comment by neupaneanish** [comment]
Thanks now i can installed HAXM after Windows Sandbox disabled and set the bios to the default  and its work.

**Comment by coxuintel** [comment]
Thank you for helping us figure out another system requirement to run HAXM. Windows Sandbox was in the Windows 10 insider ring and just published in the semi-annual channel recently. We'll update release notes soon.

**Comment by hckhanh** [comment]
Oh, you saved my day!

**Comment by charlierm** [comment]
@coxuintel you are an absolute hero!!!

**Comment by sabahang** [comment]
I have sandbox disabled but running into the same issue. I'm using WSL2 and am on insider program. Could that be cause?

**Comment by coxuintel** [comment]
WSL2 running on Hyper-V so have to disabled it as well.
