### ISSUE TITLE
Does HAXM/QEMU allow GPU or PCI passthrough?

### ISSUE THREAD

**Issue by PhillipVoyle** [intel/haxm#220]
Hi Team,
Does the HAXM/QEMU combo allow PCIe passthrough or Graphics Acceleration? I'm using a windows host, and would like to run nvidia-docker/minikube containers against a linux VM. Some guidance on whether this is possible using the HAXM/QEMU combo on windows would be helpful, and if so some information to get started would be good.  

Thanks for the info.

**Comment by coxuintel** [comment]
The key is how to prevent host using the pass through devices while assigned to guest. In Linux/KVM, you have vfio-pci. In Windows, you need a pci bus level driver which controls how host access the attached device. It's feasible and I know some scenarios do similar tricks. However since Windows is not open sourced, customizing kernel behavior has lots work to do. You can choose Discrete Device Assignment from Hyper-V [DDA](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda) for PCI device passthrough, however QEMU/HAXM can't provide alternative solution on Windows at this moment.

**Comment by PhillipVoyle** [comment]
Ok, great. Thanks for the info. Looks like I'll be dual booting for now.

**Comment by ogamespec** [comment]
When it will be added?

**Comment by coxuintel** [comment]
> When it will be added?
I'm afraid at this moment we can only reply on Windows implementation, like DDA. It's quite difficult for 3rd party vendor to modify Windows kernel to prevent OS accessing GPU. In Linux world things are simple, just enable VT-d and unbind the device from host usage.

**Comment by ogamespec** [comment]
I don't need to passthrough GPU. I need to bypass custom real PCI device, which is not used by Windows.

**Comment by coxuintel** [comment]
> I don't need to passthrough GPU. I need to bypass custom real PCI device, which is not used by Windows.

GPU is also a PCI device. Of course with a non-GPU PCI device, you do need worry OS will access it unconditionally, however you need some mechanism so that generic device enumeration won't touch the device, but pass through to QEMU right? Even windows doesn't use it, the pci/acpi driver will still enumerate it and build device/driver stack.

Have you checked this?
https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-for-deploying-devices-using-discrete-device-assignment

This is far beyond HAXM scope. QEMU may need implement it with a PCI lower bus filter driver, and some framework like vfio-pci on Linux.

**Comment by Marietto2008** [comment]
@coxuintel : does DDA work on Windows 10 pro or not ?

**Comment by coxuintel** [comment]
I'm not quiet sure about this. MSDN documented "Applies to: Microsoft Hyper-V Server 2016, Windows Server 2016, Windows Server 2019, Microsoft Hyper-V Server 2019".

https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda

You may follow this thread see if can get formal response from Microsoft:
https://social.technet.microsoft.com/Forums/en-US/4069f3cf-559d-4f87-9247-25076535707f/windows-10-virtual-machines-and-dda-for-gpus?forum=win10itprovirt

**Comment by Marietto2008** [comment]
hello. thanks. what are the hardware requisites to enable the DDA on Windows server 2016 or 2019 ?

**Comment by coxuintel** [comment]
> @coxuintel : thanks. what are the hardware requisites to enable the DDA on Windows server 2016 or 2019 ?

I thought it depends on Windows as well.

**Comment by Marietto2008** [comment]
ok but what are the hardware`s ones ?

Il ven 15 mag 2020, 10:27 Colin Xu <notifications@github.com> ha scritto:
