### ISSUE TITLE
IntelHAXM_7.3.2, Certificate Expired

### ISSUE THREAD

**Issue by pcstory** [intel/haxm#222]
Failed installation via Android Studio. 

→ cat /private/tmp/haxm_silent_run.log
/dev/disk6          	GUID_partition_scheme
/dev/disk6s1        	Apple_HFS                      	/Volumes/com_intel_kext_haxm_disc
mpkg_file=/Volumes/com_intel_kext_haxm_disc//IntelHAXM_7.3.2.mpkg
ecx 7ffafbff
edx 2c100800
edx 2c100800
No emulator instance exist!
haxm-isDowngrade: installed version of Intel HAXM found = 7.3.2; current version = 7.3.2
current version is the same or newer than existing one
Intel HAXM: This is a re-installation (chnage of memory limit)
installer: Warning - Intel Hardware Accelerated Execution Manager is already installed on this computer. If you continue installation, the Intel HAXM will be re-installed.
installer: Package name is Intel(R) Hardware Accelerated Execution Manager
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
"disk6" ejected.
Error: The installation-check script run failed !
*************** Silent installation failed ! ****************

Related - https://github.com/intel/haxm/issues/219

**Comment by wcwang** [comment]
Thanks for your report. Could you please provide the macOS information in details? And you could try the latest release HAXM v7.5.1 to install instead.

**Comment by ttimzhou** [comment]
I came across the same problem. I am using an imac with i5 processor.

**Comment by sc0ttdav3y** [comment]
This issue may get more traffic shortly because the latest Android Studio 3.4.2 ships with this version of HAXM. Reference to their issue tracker: 
https://issuetracker.google.com/issues/138132313

Also, for what it's worth, I tried running the latest 7.5.1 installer and MacOS Mojave blocks it because it "can't verify the identify of the developer". I assume the same certificate may be being used for that release?

For those with this problem, I got it installed with these steps:

1. Install the latest 7.5.1 release from the releases page on this repo
2. Unpack the zip file
3. In terminal, `cd` into the unzipped directory
4. Run `sudo ./silent_install.sh`
5. Enter your password for sudo
6. Mac will then tell you it blocked the installation of the extension; follow the link into System Preferences and click "Allow" for the script, and then "Open" for the executable "HAXM installation" and accept the security advisory.
7. After about a minute or so, the CLI will report "Silent installation Pass!"

**Comment by wcwang** [comment]
Thanks for your reply. As you mentioned, HAXM v7.5.1 used the new certificate as the previous one was expired. Meanwhile, macOS Mojave 10.14.5 introduced a [new feature](https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_5_release_notes) named notarization for kernel extensions. HAXM had been supported this feature since v7.5.1. The steps you followed are correct according to the [note](https://developer.apple.com/library/archive/technotes/tn2459/_index.html). Moreover, Android Studio will upgrade HAXM in SDK tools to the newest version to resolve this issue soon.

**Comment by goesbysteve** [comment]
Hit this today but I followed @sc0ttdav3y advice. Thanks for that. I didn't have to use terminal as the regular installer worked fine for me on Mojave.

**Comment by pcstory** [comment]
Sorry for the late replied. 
I am using Mac. 

Found a way to install it... 

1. cd ~/Library/Android/sdk/extras/intel/Hardware_Accelerated_Execution_Manager
2. Edit silent_install.sh, around line 545... add "-allowUntrusted"
... ..
installer -pkg $mpkg_file -allowUntrusted -target /  1>>$logfile  2>&1
... ...
3.  Rerun  silent_install.sh.
