### ISSUE TITLE
Windows Installer is buggy - warns of unauthorized symbols in path

### ISSUE THREAD

**Issue by marxenegls** [intel/haxm#263]
**Describe the Bug**
Installation process fails with claiming the extraction failed and the folder , which the installer itself is configured to name, has symbols that aren't supported - 
luckily it then pops up a file manager which allows to manual name and point towards the temp folder.
i eventually managed by first creating a temp folder within the the apps path and use that for the unpacking - only then it proceeds to launch the intel installer and finishes the process -
I have tried three different versions and i only persisted because i know I've managed to install it in the past version (haxm_windows-r05 2015)
 
There also seems to be a permission issue because the process only proceeds if the temp folder in which it unpacks has to be within the app's direct path / subfolder 
I tried installing in android studio's extra folder and failed even from an elevated prompt 
I then pointed to temp dir and that failed too and even within cygwin's home dir (thought cygwin could handle the symbols in the path)
 

Summary: I assume that while extracting the pkg the version details such as  decimals and underscores are default behavior of 7-zip   in naming temp folder .
exits with warning of unauthorized symbols 
yet the log says it has installed successfully , though
sc query intelhaxm clearly fails to find the service 

**Host Environment**
 - i7 

* HAXM version: 7.3.2 

* Host OS version: win7 

* Host OS architecture: x86\_64

* Host CPU model: i7 Clarksfield 

* Host RAM size: 16Gb

* (Optional) Host computer model: Dell/Alienware m15x

**Comment by wcwang** [comment]
Thanks for your report. Could you help to confirm whether it is the below known issue? On Windows 7 Service Pack 1, it is required to install Microsoft security update KB3033929 first in order to upgrade HAXM.
If the patch exists, could you manually uninstall HAXM from the Control Panel first and then download the latest release installer from [GitHub](https://github.com/intel/haxm/releases) and try again.
If possible, you may paste the screenshot and the installation logs located at %USERPROFILE%\AppData\Local\Temp\haxm_install-yyyymmdd_hhmm.log for our reference. Thanks.

**Comment by marxenegls** [comment]
I don't remember how I proceeded but I do have haxm ,I think version 7.4 , can't check right now,  running on win7 for some time. Sorry
