### ISSUE TITLE
Intel virtualization technology error

### ISSUE THREAD

**Issue by carsonf75** [intel/haxm#266]
Every time I try to install HAXM it pops up with a error that says "this computer does not support Intel virtualization technology"
![15821665874512872523212633073137](https://user-images.githubusercontent.com/61259956/74895895-db557c80-5360-11ea-8d5c-838833ea4f46.jpg)

**Comment by wcwang** [comment]
Thanks for your reporting. Could you provide more information based on the template on reporting issues? Or double check the [environment requirement](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows) on your system again.

**Comment by sannyi** [comment]
I also have this problem with a i5-7200u cpu which should have the required features according to ark.intel.com

**Comment by wayne-ma** [comment]
Hi @sannyi @carsonf75 ,could you also check the status of hyper-V,WHPX,WSL2 on your system?BTW, what's your host OS version? As I am not sure about your system configuration, maybe I can give you some suggestions for a try first.
1. Make sure the Intel-VT was enabled in BIOS;
2. Check the status of hypver-V, WHPX, Sandbox, WSL2 and disable them since these apps conflict with HAXM on windows. Refer to the [Tips and Tricks](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows#Tips_and_Tricks) wiki page.
3.Run the cmd 'bcdedit /set hypervisorlaunchtype off' in windows command prompt terminal with administrator privilege then reboot you host. Then try to install HAXM again.
Hope above steps could resolve your issue.

**Comment by sannyi** [comment]
Hi @wayne-ma ! Thank you for your help. I had VTD and VTX in my bios enabled but the main reason I had issues was probably my BIOS version. With all the features you described disabled, it still wouldn't work, but then I decided to upgrade my laptop's BIOS (I never do that on a single BIOS chip board). With the new BIOS I loaded the BIOS' defaults and then it suddenly started working. Curiously I didn't have problems when I installed it with Visual Studio Installer, only with Android  Studio and standalone HAXM I experienced issues.

**Comment by wayne-ma** [comment]
Hi @sannyi ,good to know your issue was resolved. If you are using a dell laptop,I am afraid this is a known Bios issue #226 which was brought by Dell PC.Anyway, it is really good news that you could enjoy the haxm again:)

**Comment by sannyi** [comment]
Hi! I am using an Acer A515-51G 59P4 laptop, but the BIOS problem is simmilar.

**Comment by wayne-ma** [comment]
> Hi! I am using an Acer A515-51G 59P4 laptop, but the BIOS problem is simmilar.

Ohmm, it is interesting and seems BIOS caused trouble sometimes, maybe I should summarize to the tips or known issue page. Thanks so much for your sharing.

**Comment by wayne-ma** [comment]
@carsonf75 , not sure if your issue was resolved with my instruction. If yes, let's close this issue here.
