### ISSUE TITLE
Unable to run `make install`

### ISSUE THREAD

**Issue by alessiosavi** [intel/haxm#275]
Summary: 
The folder `/etc/modules` is not found

**Host Environment**

* HAXM version: 7f3aaab42efb89bfc6d5e116da762cf33c5915fe

* Host OS version: Fedora release 31 (Thirty One)

* Host OS architecture: Linux  5.5.8-200.fc31.x86_64  GNU/Linux

* Host CPU model: 
```text
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
stepping	: 4
microcode	: 0x2e
cpu MHz		: 1369.525
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap intel_pt xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4390.23
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
```

* Host RAM size:  16

* (Optional) Host computer model: 	
Manufacturer: LENOVO
Product Name: 20DT001NIX
Version: ThinkPad L450

**To Reproduce**

1.  git clone --recursive https://github.com/intel/haxm.git
2.  cd hax/platforms/linux/
3.  make install

**Expected Behavior**
Module installed without error message

**Reproducibility**

Can't estimate

**Diagnostic Information**
```text
make -C /lib/modules/5.5.8-200.fc31.x86_64/build M=$PWD modules_install
make[1]: Entering directory '/usr/src/kernels/5.5.8-200.fc31.x86_64'
cat: /opt/SP/software/haxm/platforms/linux/modules.order: No such file or directory
  DEPMOD  5.5.8-200.fc31.x86_64
make[1]: Leaving directory '/usr/src/kernels/5.5.8-200.fc31.x86_64'
./haxm-install.sh
modprobe: FATAL: Module haxm not found in directory /lib/modules/5.5.8-200.fc31.x86_64
sed: can't read /etc/modules: No such file or directory
HAXM successfully installed
```

Host crash dump: 

HAXM log: 

Android Emulator or QEMU log: 
No log from dmesg.

Log from journalctl:

```text
Mar 15 13:47:24 localhost.localdomain groupadd[18789]: new group: name=haxm, GID=1002
Mar 15 13:47:24 localhost.localdomain groupadd[18789]: group added to /etc/gshadow: name=haxm
Mar 15 13:47:24 localhost.localdomain groupadd[18789]: group added to /etc/group: name=haxm, GID=1002
```

Screenshots: 

**Additional context**

None

**Comment by maronz** [comment]
I believe your system hasn't got the kernel headers installed (which is a prerequisite to build any kernel module).

I have not used Fedora Core for many years (and after my experience today I most certainly won't be changing this in  a hurry). But, I was curious after I saw this issue being reported, and I believe now that:
    **`sudo dnf install -y kernel-devel`**
should fix this problem for you.

As I was using the FC31 ISO as a 'liveuser' (in a VBox VM) the kernel was still v5.3.7. I therefore had to download an [older version](https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/31/Everything/x86_64/os/Packages/k/kernel-devel-5.3.7-301.fc31.x86_64.rpm) and then install that file with:
    **`sudo dnf install -y kernel-devel-5.3.7-301.fc31.x86_64.rpm`**
Of course I also had to install 'make' and 'nasm' with:
    **`sudo dnf install -y make nasm`**
I then encountered a minor bug in the makefile, which I've tried to address with:
    **`sed -i '/^modules_install:/s#$# modules#' Makefile`**
( NOTE: Otherwise one would have to use: `make && sudo make install`)

I did all this in a VM, in which I had forgotten to enable nested VT-x. I therefore could not load the successfully built 'haxm.ko' module, but I'm reasonably confident you should give it another try.

**Comment by coxuintel** [comment]
The install script on Linux only provides a demo but not verified on all distros & configurations as formal production. You'll have to modify the script to make it work through for your own environment.

Actually you can use more simple steps for using:
```bash
cd ./platform/linux
make
insmod haxm.ko
# Do sth.
rmmod haxm.ko
```
