### ISSUE TITLE
HAXM does not work with Core 2 Duo CPU

### ISSUE THREAD

**Issue by dmarjanovic** [intel/haxm#30]
I run Android emulator (latest Android development tools) with HAXM 7.0.0 and it looks like HAXM acceleration is not working since emulator boots really slowly e.g. it takes hours to boot and CPU usage is close to 100% all the time. Any idea how to proceed and diagnose problems with HAXM? 

In emulator log it says:
`Warning: Quick Boot / Snapshots not supported on this machine. A CPU with EPT + UG features is currently needed. We will address this in a future release.`
`emulator: CPU Acceleration: working`
`emulator: CPU Acceleration status: HAXM version 7.0.0 (4) is installed and usable.`

Is this message coming from HAXM? How can I be sure that bug is or is not in HAXM? Any hint where to look? Full log attached.

Is there some debug mode in HAXM? Should I try to build locally on my computer some custom build for debugging purposes? How can I install built intelhaxm.kext, do I need to package it to .dmg? If so, how? Any hint is welcome. Thank you!

`$ kextstat | grep intel`
`207    0 0xffffff7f83bbd000 0x1e000    0x1e000    com.intel.kext.intelhaxm (7.0.0) 823315F2-1275-377E-AFF9-E909857C3B2B <7 5 4 3 1>`

[emulator.log](https://github.com/intel/haxm/files/1798168/emulator.log)

macOS 10.13.3, MacBook mid 2010, Core 2 Duo 2.4GHz, 16GB RAM, 500GB SSD

EDIT: it doesn't work on Win 10 neither.

**Comment by mifritscher** [comment]
Hmm, https://software.intel.com/en-us/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-mac-os-x seems to miss one thing: regarding to https://www.qemu.org/2017/11/22/haxm-usage-windows/ , EPT is needed. EPT is not supported by Core 2 Due CPUs, only by Westmere CPUs.

**Comment by dmarjanovic** [comment]
I will check these articles, thank you.

Actually it works fine with 16GB of RAM.

**Comment by raphaelning** [comment]
@dmarjanovic Unfortunately, HAXM won't work well on your 2010 MacBook. The message you quoted (or the entire emulator.log) is from Android Emulator (which is an application/process) instead of HAXM (which is a kernel extension), and is not directly related to the slowness you are experiencing. But it does point out the fact that your CPU (Core 2 Duo) lacks two hardware virtualization features, namely Extended Page Tables (EPT) and Unrestricted Guest (UG). These features are available on all Core i-3/5/7 CPUs, but not on older models like Core 2 Duo.

EPT is crucial for memory virtualization performance. As you know, Android runs in a virtual machine as a guest OS, and therefore cannot see the 16GB of RAM in your host system. Instead, the guest RAM is virtualized by the hypervisor (HAXM) using a buffer (usually 1.5GB) allocated by the Android Emulator (or QEMU) process. Without EPT, HAXM intercepts pretty much every guest RAM access and redirects it to the buffer, which is just too much overhead and slows down the virtual machine dramatically. EPT eliminates this performance bottleneck by allowing guest RAM accesses to be handled by hardware without hypervisor intervention.

Moreover, EPT really simplifies the hypervisor implementation of memory virtualization. I believe the original authors of HAXM also preferred EPT, and did not implement the best non-EPT solution: they chose vTLB, yet there are faster (but probably more complex) algorithms for memory virtualization without EPT. As the current HAXM team, our priority is to improve the EPT code, and will eventually remove support for vTLB due to the code complexity and prevalence of EPT hardware.

In fact, I believe Android Emulator will soon require the UG feature, which is equivalent to requiring EPT since these two always come together. That requirement was first added to QEMU (so as to simplify HAXM support code in QEMU), and it seems Google has rebased Android Emulator onto the latest QEMU upstream. The article @mifritscher mentioned is about using HAXM with QEMU, so it was right about the EPT requirement.

**Comment by dmarjanovic** [comment]
Thank you for very detail answers, all is clarified now. Just to follow up with my conclusions with currently available Android development tools (tools 26.1.1, emulator 27.1.12, platform-tools 27.0.1):
- Android Emulator (engine auto/qemu2) will not work nicely with x86 AVDs OS v5.0 or newer
- Android Emulator (engine auto/qemu2) works just fine with x86 AVD OS v4.4
- the same is on both macOS 10.13.3 and Windows 10 64bit
- Android Emulator support for engine classic is broken and can't be used

**Comment by rbrisita** [comment]
Just to add: x86 AVD OS v5.0 is Google API Level 21+.

**Comment by EricYoungdale** [comment]
I just ran into this myself.  Might I suggest that instead of blue screening the system, that a more friendly type of error check would be warranted?  Just a thought.

**Comment by VanshajDaga** [comment]
Same thing happens to me on i3-3227U. Is it not having EPT + UG?

**Comment by HaHoYou** [comment]
This contains EPT, which is your details, versions, steps and logs?

**Comment by Bagusa4** [comment]
> @VanshajDaga This contains EPT, which is your details, versions, steps and logs?

I had same problem on i3-2370M, here is the log come from android studio

```
8:05 PM	Emulator: emulator: ERROR: Running multiple emulators with the same AVD is an experimental feature.

8:05 PM	Emulator: Process finished with exit code 1

8:05 PM	Emulator: Warning: Quick Boot / Snapshots not supported on this machine. A CPU with EPT + UG features is currently needed. We will address this in a future release.

```

**Comment by csxcode** [comment]
Same Problem with I3-2350M 
Emulator: Warning: Quick Boot / Snapshots not supported on this machine. A CPU with EPT + UG features is currently needed. We will address this in a future release.

**Comment by yuricamara** [comment]
Same problem here with **i3-3217U**. 

@raphaelning , maybe you mean "These features are available on all Core i-5/7 CPUs", not?

**Comment by HaHoYou** [comment]
Yes, yours has it. What is your 'same problem'? Is it 'HAXM acceleration is not working since emulator boots really slowly e.g. it takes hours to boot and CPU usage is close to 100% all the time. '? And what is your everything's version? E.G. Emulator, HAXM, host OS?

**Comment by kscott5** [comment]
Hey @raphaelning , I read the details above, but the [Manual for Windows ](https://github.com/intel/haxm/blob/master/docs/manual-windows.md)suggest

"the legacy code that enables HAXM to work in non-EPT and non-UG modes may be removed soon." 

If this statement is true. How can I determine if the non-ept and non-ug modes are available for the **master** branch or tag. I would clone and compilation local it for my development? 

If its not too late to ask for help locating a branch to clone, modify and compile locally.
