### ISSUE TITLE
Last ubuntu 16.04 kernel does not work.

### ISSUE THREAD

**Issue by mifritscher** [intel/haxm#31]
If I use the iso from http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/mini.iso (better: extract the kernel and initrd) it starts, but I get a VCPU shutdown requests after a few seconds and it hangs completely.  The version of http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-amd64/current/images/xenial-netboot/mini.iso (trusty with current(?) xenial kernel and http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/mini.iso (original xenial) are working fine. It works fine without haxm. I appended "nofb fb=false" to speed up things.

I'm using hax 7.0 + https://qemu.weilnetz.de/w64/qemu-w64-setup-20171217.exe .

**Comment by mifritscher** [comment]
Seems to be at least linked to https://github.com/intel/haxm/issues/22 , because at least in the case of the installed OS, it crashes also after printing "Loading compiled-in X.509 certificates" ...

**Comment by mifritscher** [comment]
Does this have something to do with the meltdown/spectre mitigations?

**Comment by mifritscher** [comment]
Jep, pti=off does indeed workaround this problem. Needless to say that this is _no_ correct solution.

**Comment by mifritscher** [comment]
It works much better, but not completely. qemu just exists with errorcode 0 at the and of installing a minimal Ubuntu 16.04.4 - right after creating the user accounts. The "original" Ubuntu 16.04 works.

**Comment by raphaelning** [comment]
Yes, the "VCPU shut down request" crash should be caused by the kernel PTI patches. Thankfully this HAXM patch has fixed it: #24 - we welcome more contributions like this :) We'll release HAXM 7.1.0 later this week and it will include the said patch.

I just repeated your test with HAXM 7.1.0, and was able to see the "Select a language" prompt, so the boot was fine. I haven't tried to complete the OS installation, though, but I guess the second crash you described (after user account creation) is caused a separate bug.

BTW, I'm just running QEMU from the default Windows shell (command prompt), and I get a lot of garbled text around the language selection prompt, which I think should be color codes instead. Do you see the same? Is there any way to get the installer UI displayed correctly?

**Comment by mifritscher** [comment]
Hi, ah, very nice! Could you provide the "prerelease" 7.1.0 or should I just wait a few days?
Hehe, I always append a "nofb fb=false" (aka: even before haxm), because else the GPU output is very slow - and this way I could use the curses interface later to redirect the output elsewhere. I think that should help you as well :-) I'm using the normal prompt as well, but qemu starts a seperate window for the GUI. Btw, the minimal installation goes in ca. 20 minutes, if you use a preallocated HDD image. So rather fast :-)

**Comment by mifritscher** [comment]
I tried it without the nofb-settings, and got no garbage. But I could only test the "original" 16.04 kernel, not the updated because of the crash.

**Comment by mifritscher** [comment]
I can confirm than 7.1.0 fixes the boot problem for me! Many thanks! The installation is running now, I'll report the result as soon it is finished.

**Comment by mifritscher** [comment]
Ok, the exit at the end is still occuring, but this is another issue. I'll just need a way to get the exact position where it stops to get an insight.

**Comment by raphaelning** [comment]
Thanks. I couldn't get rid of the garbled text on Windows. I've tried another shell (git-bash.exe), which fixes the display issue but doesn't handle keyboard input correctly, so the installer is still unusable. My colleague told me the Cygwin shell has the same problem. Could you provide the full QEMU command line you are using?

On Mac, the installer is usable, so I just tested the installation. In the end I got a kernel installation failure, which is part of the _Install the base system_ step:

```
      │  Choose language                                                 │
      │  Access software for a blind person using a braille display      │
      │  Configure the keyboard                                          │
      │  Detect virtual driver disks from hardware manufacturer          │
      │  Detect network hardware                                         │
      │  Configure the network                                           │
      │  Choose a mirror of the Ubuntu archive                           │
      │  Download installer components                                   │
      │  Set up users and passwords                                      │
      │  Configure the clock                                             │
      │  Detect disks                                                    │
      │  Partition disks                                                 │
      │  Install the base system                                         │
      │  Configure the package manager                                   │
      │  Select and install software                                     │
```

It shouldn't be a HAXM issue. Maybe it's because I underestimated the disk space requirement and only used a 1GB disk image. Did you complete all of the above steps, or did you fail at _Set up users and passwords_?

**Comment by mifritscher** [comment]
I failed after "Select and install software", round about "Setup users and passwords". But it is too fast to really determinate it.

Regarding the command line: 
"qemu_windows_x64\qemu-system-x86_64.exe"  -enable-hax -m 1024 -drive file=temp.vmdk,if=virtio -vga virtio -device virtio-net,netdev=natted -netdev user,id=natted -kernel linux_initrd/linux -initrd linux_initrd/initrd.gz -append "nofb fb=false"

The size of the temp.vmdk is 4 GB. I'm running on Windows 7 64 bit.

**Comment by mifritscher** [comment]
Ok, the manual installation works (minimal installation, only extra was the ssh server) - so it seems to have a problem with the things in the unattended setup for me.

**Comment by raphaelning** [comment]
OK great. Thanks for introducing us to this test case.
