### ISSUE TITLE
v7.6.5 Cannot Install on Mac Catalina  

### ISSUE THREAD

**Issue by djcyr** [intel/haxm#324]
Is it possible to get a build working for Mac Catalina?  The latest dist v7.6.5 does not seem to be working after install. 

I tried 
kextstat | grep intel
and see nothing.

Furthermore, the android emulator gives no indication that HAXM is being utilized.

Thanks for all your work that you have already put into this project!

**Comment by wcwang** [comment]
Since macOS Catalina 10.15, Kernel Extension is no longer supported to be installed by Apple. Instead, it is replaced by **System Extensions**, which requires to rewrite the driver framework. We are evaluating the workload. Please use **HVF** instead during this period. Sorry for bringing you the inconvenience, thank you for your attention to HAXM.

**Comment by Mouradif** [comment]
Hi @wcwang what's HVF ? Could you provide a link please ?

**Comment by wcwang** [comment]
@Mouradif, thanks for your question. The QEMU HVF feature can be found [here](https://wiki.qemu.org/Features/HVF). Currently, HVF is the default hypervisor for macOS, you may try to remove the parameter of '-accel hax' from the command line to launch QEMU or add '-accel hvf' instead. Thanks.
