### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by kurianCoding** [intel/haxm#58]
trying to build this on os 10.9
I did `xcodebuild -config Release -sdk macosx10.9`
getting this error
`clang: error: unknown argument: '-fstack-protector-strong`

xcode version 6.2(6C131e)

**Comment by AlexAltea** [comment]
@kurianCoding The prerequisites to build HAXM on macOS (see [*README.md*](https://github.com/intel/haxm#prerequisites-1)) are
- Xcode 7.2.1 or later (but you are using 6.2)
- macOS 10.10 SDK or later (but you are using 10.9, which is as of HAXM v7.2.0 not supported [[3]](https://github.com/intel/haxm/releases/tag/v7.2.0)).

You will need to update Xcode and either update your system or cross-compile to a higher macOS by downloading the SDKs, if possible.


@raphaelning Unless this issue is replicated on Xcode 7.2.1+ or macOS 10.10+, it should be closed.

**Comment by kurianCoding** [comment]
@AlexAltea Yes, I am not able to upgrade to higher macOS, since I am using a very old macbook. haxm gets built with the suggestion that @raphaelning gave, but when running android vritual machine, Android studio prompts to install an updated version, and then fails to install pending the requirement for newer OS. The latest OS i can run is mavericks (10.9.5).

**Comment by raphaelning** [comment]
Thanks, @AlexAltea .

> but when running android vritual machine, Android studio prompts to install an updated version

An updated version of Android Studio or Android Emulator? They are largely independent of each other, so you should be able to keep your old Android Studio and install the latest Emulator (by downloading the latest Android SDK tools). Anyway, since your original problem is solved, I'll close this issue.
