### ISSUE TITLE
15:27	Emulator: emulator: ERROR: x86 emulation currently requires hardware acceleration!

### ISSUE THREAD

**Issue by kaushik199501** [intel/haxm#77]
15:27	Emulator: emulator: ERROR: x86 emulation currently requires hardware acceleration!
when ever i try to run the project the above error occurs. and i cant even open the virtual device from the AVD Manager

**Comment by raphaelning** [comment]
Looks like you are trying to launch an x86 or x86_64 AVD in Android Emulator. On Windows, that usually requires HAXM to be installed. Please tell us more about your host system (the PC or Mac where you run Android Studio):

1. OS architecture and version, e.g. 64-bit Windows 10 Pro v1803.
2. CPU model, e.g. Intel Core i7-8550U.
3. HAXM version (as reported by SDK Manager > SDK Tools), e.g. 7.2.0.
4. Android Emulator version (as reported by SDK Manager > SDK Tools), e.g. 27.3.8.
5. AVD API level and architecture, e.g. API 28 x86.

**Comment by kaushik199501** [comment]
Yes, I have the Following
1. Windows 10 Pro 64-bit Operating Processor
2. Intel Core i7-6500U
3. Intel x86 emulator Accelerator (HAXM installer) 7.2.0
4. Android Emulator 27.3.8
5. API 28 x86

I have all the above following yet i am unable to open the virtual device neither can i run the project
the error that appears is 
15:27	Emulator: emulator: ERROR: x86 emulation currently requires hardware acceleration!

**Comment by raphaelning** [comment]
Thanks. You seem to have HAXM installed correctly on a supported host system. Now let's find out why HAXM is not working using a command line tool that is part of Android Emulator:

1. Locate your Android Emulator installation (i.e. the directory that contains `emulator.exe`, etc.), which is usually `C:\Users\<username>\AppData\Local\Android\sdk\emulator\`.
2. Open a Command Prompt window, and `cd` into that directory.
3. `emulator-check.exe accel hyper-v`
4. Post the output here.

If the tool determines that neither HAXM nor Hyper-V is usable, you'll need to check your BIOS settings and make sure Intel Virtualization Technology (or VT-x) is enabled. Otherwise, if Hyper-V is enabled, you'll need to disable it in order to use HAXM. More details here: https://developer.android.com/studio/run/emulator-acceleration#accel-vm

**Comment by kaushik199501** [comment]
![dospromt error android](https://user-images.githubusercontent.com/41366576/42890221-e5c2959c-8ac9-11e8-91a2-35b629434d32.png)

the dospromt is showing that the Haxm is nt installed
where as in the android studio it shows that it is installed

**Comment by raphaelning** [comment]
Please try to reinstall HAXM using the standalone installer:

1. Download https://github.com/intel/haxm/releases/download/v7.2.0/haxm-windows_v7_2_0.zip
2. Unzip, and then run `intelhaxm-android.exe`.
3. If the installer detects a current HAXM 7.2.0 installation and won't reinstall it for you, you can uninstall the broken version using SDK Manager or Control Panel (Apps & Features).

**Comment by kaushik199501** [comment]
Thank You, for your help and support. Now the HAXM is installed properly and and Virtual Device is working.
Hope, that i can help someone with this problem like you did.
I am still learning to operate Android Studio, if any problem arises, i hope that i can ask here for help and you will help resolve just like this one.
Thank-you A lot.

**Comment by raphaelning** [comment]
You're welcome. FYI, Android Emulator has a built-in bug reporting mechanism: https://developer.android.com/studio/report-bugs#emulator-bugs

But you're still welcome to report HAXM-related issues here.
