### ISSUE TITLE
macOS Build Instructions need improvement

### ISSUE THREAD

**Issue by mborgerson** [intel/haxm#96]
I encountered several issues when following the build instructions for macOS and loading my unsigned build.

## Issue 1: SDKs
The Xcode project file is not configured to use the SDK that I had--this is briefly mentioned but not explicitly stated. The version which are installed can be queried with `xcodebuild -showsdks`. For me, on macOS 10.12.6, 10.13 was installed.

## Issue 2: Issue with signed kernel extensions
Apparently macOS has a security feature which prevents installation of unsigned kernel extensions. This must be disabled when building for yourself. To do this, restart into recovery mode (hold `CMD + R` during reboot), then run terminal and execute `csrutil disable`.

## Issue 3: Permission issue with loading kernel extension
Apparently the kext will not be loaded without sufficient permissions, necessitating:
```bash
sudo chown -R root:wheel intelhaxm.kext
sudo chmod -R 700 intelhaxm.kext
```

## Issue 4: Symbol resolution failure during extension loading
I got an error message stating: `The following symbols are unresolved for this kext: ... ___memcpy_chk`
This can be resolved by adding a `-D_FORTIFY_SOURCE=0` macro definition to the project. [Source](https://github.com/mryraghi/tcpcrypt)

## Issue 5: Missing instructions for loading the kernel extension
The following command must be run:
```
sudo kextutil intelhaxm.kext
```

Then the following error messages may be displayed, despite the extension actually being loaded:

```
Diagnostics for intelhaxm.kext:
Code Signing Failure: not code signed
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "intelhaxm.kext"
kext signature failure override allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/path/to/haxm/darwin/hax_driver/com_intel_hax/build/Debug/intelhaxm.kext"
```

The extension can be unloaded with:

```
sudo kextunload intelhaxm.kext
```

Thanks!

**Comment by raphaelning** [comment]
Thanks for the detailed report. Indeed, we only wrote instructions for building the KEXT, but not for loading/testing the KEXT, hence issue 2 & 3. Sorry about that!

> The Xcode project file is not configured to use the SDK that I had

Yes, we intentionally hard-code SDK 10.10 in the build configuration, because a) we want the generated KEXT to be compatible with macOS >= 10.10, and a) different people have different SDK versions installed. But I admit that we should explain this better in the document.

> I got an error message stating: The following symbols are unresolved for this kext: ... ___memcpy_chk

Hmm, we've never seen this issue. So IIUC, does this happen only when you use the `Debug` (default) build configuration? Have you tried `xcodebuild -configuration Release -sdk macosx10.13`?

**Comment by mborgerson** [comment]
@raphaelning I tried both and both configurations appear to have the issue.

**Comment by raphaelning** [comment]
I still can't reproduce this issue. I think that's because my macOS kernel has that symbol:

```
$ nm -a /System/Library/Kernels/kernel | grep ___memcpy_chk
ffffff8000346140 T ___memcpy_chk
```
The link you referenced claims that this symbol is missing from "development" or "debug" kernels:

> My guess is that those symbols are not available when using a development or a debug kernel in the testing machine.

So do you build your own kernel? I just use the official kernel. Or does switching to recovery mode or turning off SIP result in a different kernel to be loaded? If so, where is that kernel image?

In addition, defining `_FORTIFY_SOURCE=0` does make sense for the Debug build (since `_FORTIFY_SOURCE` is ineffective when used in conjunction with `-O0`), but isn't it equivalent to not defining `_FORTIFY_SOURCE` at all, which I think should be the default behavior?
